<?php

namespace App\Controllers;

use App\Controllers\BaseController;
use CodeIgniter\HTTP\ResponseInterface;
use Dompdf\Dompdf;

class Domppdf extends BaseController
{
    public function index()
    {
        $html = '<h1>Sales Report</h1><p>Generated by Dompdf in CodeIgniter.</p>';
        $pdf = new Dompdf();

        $pdf->loadHtml($html);
        $pdf->setPaper("A4", "portrait");
        $pdf->render();
        $pdf->stream("sales_report.pdf", ["Attachment" => true]);
    }
}

exit();
